chore: update from master to main

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -3,11 +3,10 @@ name: Pull Request
 on:
   pull_request:
     branches:
-      - master
-      - develop
+      - main
 
   repository_dispatch:
-    types: [pull-request-develop, pull-request-master]
+    types: [pull-request]
 
 jobs:
   checkout-and-build-pr:
@@ -73,7 +72,21 @@ jobs:
       - name: Run eslint-check and generate report
         id: eslint-check
         run: |
-          npm run eslint-check
+          npm run eslint-check -- --output-file eslint_report.json --format json
+        continue-on-error: true
+
+      - name: Annotate Lint Results
+        uses: ataylorme/eslint-annotate-action@1.0.4
+        with:
+          repo-token: ${{ secrets.GITHUB_TOKEN }}
+          report-json: eslint_report.json
+        continue-on-error: true
+
+      - name: Check eslint-check outcome
+        if: steps.eslint-check.outcome != 'success'
+        run: |
+          echo "::error::eslint-check failed. View output of _Run eslint-check and generate report_ step"
+          exit 1
 
   test:
     name: test
@@ -114,7 +127,7 @@ jobs:
         uses: actions/checkout@v2
 
       - name: Validate Open Source Files
-        uses: newrelic/validate-nerdpack-action@v1.0.2
+        uses: newrelic/validate-nerdpack-action@v1
 
       - name: Install NR1 CLI
         run: |
